# Generated by Django 5.0.13 on 2025-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0018_remove_xy_belong_nation_remove_photo_belong_xy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Money',
            field=models.IntegerField(blank=True, default=0, max_length=255, null=True, verbose_name='Tiền'),
        ),
    ]
