# Generated by Django 5.0.13 on 2025-06-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0019_alter_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='Status',
            field=models.BooleanField(blank=True, max_length=50, null=True, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='Value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Giá trị'),
        ),
    ]
