# Generated by Django 5.0.13 on 2025-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0020_transaction_history_status_transaction_history_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price_one', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giá 1 lần')),
                ('Price_month', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giá 30 ngày')),
                ('Order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Bảng giá',
                'ordering': ['id'],
            },
        ),
    ]
