# Generated by Django 5.0.13 on 2025-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0022_price_list_delete_list_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_list',
            name='Price_month',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True, verbose_name='Giá 30 ngày'),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='Price_one',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True, verbose_name='Giá 1 lần'),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='Status',
            field=models.IntegerField(blank=True, default=2, max_length=50, null=True, verbose_name='Trạng thái'),
        ),
    ]
