# Generated by Django 5.0.13 on 2025-06-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0023_alter_price_list_price_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count_keyword', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số từ 1 ngày')),
                ('Now_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Bảng giá',
                'ordering': ['id'],
            },
        ),
    ]
