# Generated by Django 5.0.13 on 2025-06-04 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0025_keyword_belong_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='Belong_User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_Keyword', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='time_user',
            name='Belong_User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_Time_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
