# Generated by Django 5.0.13 on 2025-07-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0027_price_list_keyword_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Key')),
                ('Order', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'API key',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='keyword',
            name='Count_keyword',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số từ 1 ngày dã sử dụng'),
        ),
    ]
